---
tap_install:
  values:
    profile: build
    ceip_policy_disclosed: true

    shared:
      ingress_domain: build.tapsme.org
      image_registry:  
        project_path: "registry.harbor.learn.tapsme.org/tap-build"

    supply_chain: testing_scanning
    
    ootb_supply_chain_testing_scanning:
      external_delivery: true
      gitops:
        deliverable_repository_owner: "x95castle1"
        deliverable_repository_name: "tap-gitops-deliverable"
        deliverable_branch: main
        deliverable_server_address: "ssh://git@github.com"
        ssh_secret: "git-auth"
        server_address: "ssh://git@github.com"
        repository_owner: "x95castle1"
        repository_name: "tap-gitops-config"
        branch: main
  
    grype:
      namespace: dev
      targetImagePullSecret: "registries-credentials"
      metadataStore:
        url: "https://metadata-store.view.tap.raltaf.io"
        caSecret:
          name: store-ca-cert
          importFromNamespace: metadata-store-secrets
        authSecret:
          name: store-auth-token
          importFromNamespace: metadata-store-secrets

    scanning:
      metadataStore:
        url: ""

    package_overlays:
    - name: "ootb-supply-chain-testing-scanning"
      secrets: 
      - name: "ootb-supply-chain-overlay"
    - name: "ootb-templates"
      secrets: 
      - name: "ootb-template-overlay"  

